[package]
name = "stm32f107"
version = "0.1.0"
authors = ["Sam Voss <sam.voss@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.stm32f1]
version = "0.13.0"
features = ["stm32f107", "rt"]